# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tfbg676-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.cache/wt [current_project]
set_property parent.project_path I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/conv_pkg.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/izhikevichtestfixed1_entity_declarations.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/xlclockdriver_rd.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/single_reg_w_init.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/srl33e.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/synth_reg.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/synth_reg_reg.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/synth_reg_w_init.vhd
  I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/imports/sysgen/izhikevichtestfixed1.vhd
}
read_ip -quiet I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i1/izhikevichtestfixed1_c_addsub_v12_0_i1.xci
set_property used_in_implementation false [get_files -all i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i1/izhikevichtestfixed1_c_addsub_v12_0_i1_ooc.xdc]

read_ip -quiet I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_mult_gen_v12_0_i0/izhikevichtestfixed1_mult_gen_v12_0_i0.xci
set_property used_in_implementation false [get_files -all i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_mult_gen_v12_0_i0/izhikevichtestfixed1_mult_gen_v12_0_i0_ooc.xdc]

read_ip -quiet I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0.xci
set_property used_in_implementation false [get_files -all i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/constrs_1/imports/sysgen/izhikevichtestfixed1_clock.xdc
set_property used_in_implementation false [get_files I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/constrs_1/imports/sysgen/izhikevichtestfixed1_clock.xdc]

read_xdc I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/constrs_1/imports/sysgen/izhikevichtestfixed1.xdc
set_property used_in_implementation false [get_files I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/constrs_1/imports/sysgen/izhikevichtestfixed1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top izhikevichtestfixed1 -part xc7k325tfbg676-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef izhikevichtestfixed1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file izhikevichtestfixed1_utilization_synth.rpt -pb izhikevichtestfixed1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
