# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0.xci
# IP: The module: 'izhikevichtestfixed1_c_addsub_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'izhikevichtestfixed1_c_addsub_v12_0_i0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: I:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0.xci
# IP: The module: 'izhikevichtestfixed1_c_addsub_v12_0_i0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/netlist_fixed/hdl_netlist/izhikevichtestfixed1.srcs/sources_1/ip/izhikevichtestfixed1_c_addsub_v12_0_i0/izhikevichtestfixed1_c_addsub_v12_0_i0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'izhikevichtestfixed1_c_addsub_v12_0_i0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
